sudo: required
branches:
    only:
        - master
services:
    - docker
before_install:
    - docker build -t $IMAGE .
script:
    - docker run -e BACKUP_HOME=/tmp $IMAGE
deploy:
    provider: script
    script: scripts/deploy.sh
    on:
        branch: master
